# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo $MY_SECRET_ENV_VAR
  displayName: 'Run a one-line script'
  env:
    MY_SECRET_ENV_VAR: $(MY_SECRET) 
- bash: |
    echo "My second secret variable: $FOO_TWO"
    if [ "$MY_SECRET_ENV_VAR" = "COLEGA" ]; then
        echo "Strings are equal."
    else
        echo "Strings are not equal."
    fi
    echo $MY_SECRET_ENV_VAR
  env:
    MY_SECRET_ENV_VAR: $(MY_SECRET) 